var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
var fs=require("fs"),path=require("path"),glob=require("glob"),watch=require("node-watch"),isDev="dev"===process.env.NODE_ENV,activate=process.env.activate||"_blank",rqPattern=process.env.requirePattern||"",wilokePlugin=function(a){this.includeComp={};this.includeDemo={};this.opts=Object.assign({appConfig:{},authorTree:[],beauty:"\t",styles:{updateClass:!0}},a)};
wilokePlugin.prototype.pugBasic=function(){var a=this.opts;return"//- demo: true\nmixin ComponentName(args)\n"+a.beauty+"include cssmodule\n\n"+a.beauty+"+module('div', css.module, args)\n"+a.beauty+a.beauty+"- let args = item\n"+a.beauty+a.beauty+"\n"+a.beauty+a.beauty+"\n"};
wilokePlugin.prototype.pageBasic=function(){var a=this.opts;return"extends pug/layout\n\n//- Config\nblock config\n"+a.beauty+"-\n"+a.beauty+a.beauty+"config.title = 'PageTitleBasic'\n"+a.beauty+a.beauty+"config.bodyClass = ''\n\n//- afterLink\nblock afterLink\n"+a.beauty+"\n//- Header\nblock header\n"+a.beauty+"\n//- Footer\nblock footer\n"+a.beauty+"\n//- Content\nblock content\n"+a.beauty+"\n"};
wilokePlugin.prototype.createBasicPage=function(){var a=this,b=this.opts.appConfig;watch(b.folders.path+"/"+b.folders.content+"/"+activate+"/"+b.entry.path,{recursive:!1},function(b,d){-1!==d.indexOf(".pug")&&fs.exists(d,function(b){b&&fs.readFile(d,"utf-8",function(b,c){if(b)throw b;if(""===c){var e=a.pageBasic().replace(/PageTitleBasic/g,d.replace(/(.*(\\|\/))|(\.pug)/g,""));fs.writeFile(d,e,function(a){if(a)throw a;})}})})})};
wilokePlugin.prototype.writeFilePugComp=function(a,b){var c=this;-1===b.search(/\.(js|scss|css|pug|jpg|svg|gif|png|DS_Store)/g)&&fs.exists(b,function(d){d&&fs.readdir(b,function(h,e){if(h)throw h;if(0===e.length){var d=b.replace(/.*(\\|\/)/g,""),f=a.replace(/.*(\\|\/)/g,""),k=c.pugBasic().replace(/ComponentName/g,f+"_"+d),l=b+"/"+d+".pug";fs.exists(l,function(a){a||fs.writeFile(l,k,function(a){if(a)throw a;})})}})})};
wilokePlugin.prototype.watchFolderComp=function(a){var b=this,c=fs.readdirSync(a);c=$jscomp.makeIterator(c);for(var d=c.next();!d.done;d=c.next())watch(a+"/"+d.value,{recursive:!0},function(c,e){return b.writeFilePugComp(a,e)})};wilokePlugin.prototype.filePugComp=function(a){return glob.sync(a+"/**/*.pug",{ignore:[a+"/**/cssmodule.pug",a+"/**/demo.pug",a+"/**/data.pug","DS_Store"]})};
wilokePlugin.prototype.filePugCompAndData=function(a){return glob.sync(a+"/**/*.pug",{ignore:[a+"/**/cssmodule.pug",a+"/**/demo.pug"]})};
wilokePlugin.prototype.checkPugFile=function(a){var b=this,c={};a=$jscomp.makeIterator(this.filePugComp(a));for(var d=a.next();!d.done;c={pugFile:c.pugFile,compFolder:c.compFolder},d=a.next())c.pugFile=d.value,c.compFolder=path.dirname(c.pugFile),fs.readFile(c.pugFile,"utf-8",function(a){return function(c,d){if(c)throw c;b.writeCssModuleFile(a.pugFile,a.compFolder,d);b.writeScssFile(a.pugFile,a.compFolder,d);b.writeFileDemo(a.pugFile,a.compFolder,d)}}(c))};
wilokePlugin.prototype.writeCssModuleFile=function(a,b,c){-1!==c.indexOf("include cssmodule")&&fs.exists(b+"/cssmodule.pug",function(a){a||fs.writeFile(b+"/cssmodule.pug","- css = {}",function(a){if(a)throw a;})})};
wilokePlugin.prototype.writeScssFile=function(a,b,c){var d=this.opts,h=a.replace(/\.pug/g,".scss");a=c.match(/(?:\/\/.*demo: .*(\r\n|\r|\n))(mixin(.*)(?=(\()))/g);a=null!==a?a[0].replace(/\/\/-\s*.*(\r\n|\r|\n)mixin\s*/g,""):"";var e="/* //--- "+a+"\n--------------------------------------------------------------------------------*/\n",g=function(){-1!==c.indexOf("include cssmodule")&&-1!==c.indexOf("css.")&&(new Promise(function(a,b){fs.readFile(h,"utf-8",function(b,c){if(b)throw b;var d=-1===c.indexOf(e)?
e+c:c;a([d,c])})})).then(function(a){var b=a[0];a=a[1];var g=remove_duplicates(c.match(/css\..\w*/g));g=$jscomp.makeIterator(g);for(var f=g.next();!f.done;f=g.next())f=f.value.replace(/.*\./g,""),-1===b.indexOf(f)&&(b+="\n// "+f+"\n."+f+" {\n\t\n}\n",d.styles.updateClass?a!==b&&fs.writeFile(h,b,function(a){if(a)throw a;}):a===e&&fs.writeFile(h,b,function(a){if(a)throw a;}))})};fs.exists(h,function(a){a?g():fs.writeFile(h,e,function(a){if(a)throw a;})})};
wilokePlugin.prototype.writeFileDemo=function(a,b,c){var d="//- Args:",h="",e=path.dirname(a)+"/demo.pug",g=c.match(/(?:\/\/.*demo: .*(\r\n|\r|\n))(mixin(.*)(?=(\()))/g);g=null!==g?g[0].replace(/\/\/-\s*.*(\r\n|\r|\n)mixin\s*/g,""):"";if(-1!==c.indexOf("args")&&-1!==c.search(/\/\/.*demo:\strue/g)){var f=a.replace(/\.pug/g,".scss");a=c.replace(/args.*modifier|if.*modifier/g,"").match(/(set\(\w+\D\s+\D\w+)/g);b=c.replace(/args.*modifier|if.*modifier/g,"").match(/(=|\(|&&|\|\|)\s*(args\.\w*)/g);c=[];
null!==a&&(a=remove_duplicates(a.toString().replace(/(set\(\w+)(,*\s('|"))/g," ").split(",")),c.push(a.join(",")));null!==b&&(a=remove_duplicates(b.toString().replace(/(=|\(|&&|\|\|)\s*(args\.)/g," ").split(",")),c.push(a.join(",")));d+=""+c.join(",");h='<div class="wil-core-space"><span></span><div class="wil-text-modifier"><span>default</span></div></div>\n'+d+"\n+"+g+"({\n\t\n})\n";var k=function(){fs.exists(f,function(a){a&&fs.readFile(f,"utf-8",function(a,b){if(a)throw a;var c=-1!==b.indexOf("modifier")?
b.match(/\/\/\s*modifier.*(\r\n|\r|\n).*/g).join("").match(/.*{/g):[1];c=$jscomp.makeIterator(c);for(var f=c.next();!f.done;f=c.next())f=f.value,h+="string"===typeof f?'<div class="wil-core-space"><span></span><div class="wil-text-modifier"><span>modifier: \''+f.replace(/\.|\s+\{/g,"")+"'</span></div></div>\n"+d+"\n+"+g+"({\n\tmodifier: '"+f.replace(/\.|\s+\{/g,"")+"'\n})\n":"",fs.readFile(e,"utf-8",function(a,b){if(a)throw a;b!==h&&fs.writeFile(e,h,function(a){if(a)throw a;})})})})};fs.exists(e,
function(a){a?k():fs.writeFile(e,"",function(a){if(a)throw a;})})}};wilokePlugin.prototype.writeFiles=function(a,b,c){var d=a+"/"+b+".pug";fs.exists(d,function(h){h?fs.readFile(d,"utf-8",function(d,h){if(d)throw d;h!==c&&fs.writeFile(a+"/"+b+".pug",c,function(a){if(a)throw a;})}):fs.writeFile(a+"/"+b+".pug","",function(a){if(a)throw a;})})};
wilokePlugin.prototype.checkIncludeComp=function(){var a=this.opts.appConfig,b=a.folders.path+"/"+a.folders.content+"/"+activate+"/"+a.entry.path+"/pug/includes/authorFolder",c;for(c in this.includeComp)if("undefined"!==typeof this.includeComp[c][0]){var d="include------"+this.includeComp[c].join("\ninclude------");d=d.replace(new RegExp("------.*"+a.folders.path,"g")," ");this.writeFiles(b,c,d)}};
wilokePlugin.prototype.checkIncludeDemo=function(){var a=this.opts.appConfig;a=a.folders.path+"/"+a.folders.content+"/"+activate+"/"+a.entry.path+"/pug/docs-includes/authorFolder";for(var b in this.includeDemo)if("undefined"!==typeof this.includeDemo[b][0]){var c=this.includeDemo[b].join("\n");this.writeFiles(a,b,c)}};
wilokePlugin.prototype.writefileFlag=function(a){a=this.opts.appConfig;var b=a.folders.path+"/"+a.folders.content+"/"+activate+"/"+a.entry.path;a=a.folders.path+"/"+a.folders.content+"/"+activate+"/config.js";fs.watch("app.config.js",function(){fs.writeFile(b+"/pug/flag.pug","",function(a){if(a)throw a;})});fs.watch(a,function(){fs.writeFile(b+"/pug/flag.pug","",function(a){if(a)throw a;})})};
wilokePlugin.prototype.delFileAuthor=function(a){var b=a+"/authorFolder";fs.readdir(b,function(a,d){if(a)throw a;for(var c={},e=$jscomp.makeIterator(d),g=e.next();!g.done;c={file:c.file},g=e.next())c.file=g.value,fs.exists(b+"/"+c.file,function(a){return function(c){c&&fs.unlink(b+"/"+a.file,function(a){if(a)throw a;})}}(c))})};
wilokePlugin.prototype.beforeBegin=function(){var a=this.opts,b=a.appConfig;b=b.folders.path+"/"+b.folders.content+"/"+activate+"/"+b.entry.path;var c=b+"/pug/includes/includes.pug",d=b+"/pug/docs-includes/docs-includes.pug";(new Promise(function(a,b){fs.writeFile(c,"",function(a){if(a)throw a;});fs.writeFile(d,"",function(a){if(a)throw a;});a("OK");b("Err")})).then(function(){for(var b="",e="mixin include(file)",g=$jscomp.makeIterator(a.authorTree),f=g.next();!f.done;f=g.next())f=decode(f.value).replace(/.*(\\|\/)/g,
""),b+="include authorFolder/"+f+".pug\n",e+="\n\tinclude authorFolder/"+f+".pug",fs.readFile(c,"utf-8",function(a,d){if(a)throw a;""===d&&fs.writeFile(c,b,function(a){if(a)throw a;})}),fs.readFile(d,"utf-8",function(a,b){if(a)throw a;""===b&&fs.writeFile(d,e,function(a){if(a)throw a;})})})["catch"](function(a){return console.log(a)})};wilokePlugin.prototype.emit=function(a){var b=this;a.plugin("emit",function(a,d){isDev&&b.checkIncludeDemo();d()})};
wilokePlugin.prototype.invalid=function(a){var b=this,c=this.opts,d=c.appConfig;a.plugin("invalid",function(a){a=$jscomp.makeIterator(c.authorTree);for(var e=a.next();!e.done;e=a.next())e=e.value,-1!==decode(e).search(new RegExp("_pattern(\\/|\\\\)"+rqPattern,"g"))&&(e=decode(e),b.watchFolderComp(e),b.checkPugFile(e),b.writefileFlag(e));a=$jscomp.makeIterator(c.authorTree);for(e=a.next();!e.done;e=a.next()){var g=decode(e.value);e=g.replace(/.*(\\|\/)/g,"");var f=glob.sync(g+"/**/demo.pug"),h=[];
b.includeComp[e]=b.filePugCompAndData(g);g=$jscomp.makeIterator(f);for(f=g.next();!f.done;f=g.next())f=f.value,h.push(('if (file === "------'+f+'")\n\tinclude ------'+f).replace(new RegExp("------.*"+d.folders.path,"g"),"")),b.includeDemo[e]=h}isDev&&(b.checkIncludeComp(),b.createBasicPage())})};wilokePlugin.prototype.apply=function(a){this.beforeBegin();this.invalid(a);this.emit(a)};
var encode=function(a){return(new Buffer(a)).toString("base64")},decode=function(a){return(new Buffer(a+"=","base64")).toString("ascii")},remove_duplicates=function(a){for(var b={},c=[],d=0,h=a.length;d<h;d++)b[a[d]]=!0;for(var e in b)c.push(e);return c};module.exports=wilokePlugin;